---
# tasks file for webserver
- name: Setup Apache
  hosts: node01
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
    - name: Start service
      service:
        name: httpd
        state: started
